/**
 * VectorForge - Metadata Generation Service
 * Generates listing-info.txt with substitution variable support.
 */

import fs from 'fs/promises';
import { logger } from '@/lib/logger';
import { applySubstitutions } from '@/lib/utils';
import type { SubstitutionData } from '@/lib/types';
import { getListingInfoPath } from '@/lib/output-naming';

export interface MetadataInput {
  originalFilename: string;
  baseName: string;
  sku: string;
  conversionDate: string;
  originalWidth: number;
  originalHeight: number;
  upscaledWidth: number | null;
  upscaledHeight: number | null;
  upscaleFactor: number;
  upscaleApplied: boolean;
  formats: string[];
  substitutionData: SubstitutionData;
  marketplacePreview?: boolean;
  cncMode?: boolean;
}

/**
 * Generate the listing-info.txt metadata file.
 * Includes original filename, base name, conversion date, dimensions,
 * and applied substitution data.
 */
export async function generateMetadataFile(
  outputDir: string,
  input: MetadataInput
): Promise<string> {
  const metadataPath = getListingInfoPath(outputDir, input.baseName);

  // Build the metadata content
  let content = `================================================================================
VECTORFORGE - LISTING INFORMATION
================================================================================

ITEM DETAILS
------------
Original Filename: ${input.originalFilename}
Base Name:         ${input.baseName}
SKU:               ${input.sku}
Conversion Date:   ${input.conversionDate}

DIMENSIONS
----------
Original:  ${input.originalWidth} x ${input.originalHeight} px
`;

  if (input.upscaleApplied) {
    content += `Upscaled:  ${input.upscaledWidth} x ${input.upscaledHeight} px (${input.upscaleFactor}x)
`;
  } else {
    content += `Upscaled:  Not applied (dimensions above threshold)
`;
  }

  content += `
GENERATED FORMATS
-----------------
${input.formats.map((f) => `• ${f.toUpperCase()}`).join('\n')}

PROCESSING OPTIONS
------------------
CNC/Vinyl/Laser Mode: ${input.cncMode ? 'Enabled (monochrome trace)' : 'Disabled (full color)'}
Marketplace Preview:  ${input.marketplacePreview ? 'Generated' : 'Skipped'}

`;

  // Apply substitution data
  const stringSubstitutions = Object.fromEntries(
    Object.entries(input.substitutionData).filter(
      ([key, value]) => typeof value === 'string' && !key.startsWith('__')
    )
  );

  if (Object.keys(stringSubstitutions).length > 0) {
    content += `LISTING DATA
------------
`;
    for (const [key, value] of Object.entries(stringSubstitutions)) {
      // Apply any nested substitutions within values
      const resolvedValue = applySubstitutions(value, {
        ...stringSubstitutions,
        BASENAME: input.baseName,
        SKU: input.sku,
        DATE: input.conversionDate,
        WIDTH: String(input.upscaledWidth || input.originalWidth),
        HEIGHT: String(input.upscaledHeight || input.originalHeight),
      });
      content += `${key}: ${resolvedValue}\n`;
    }
  }

  content += `
================================================================================
Generated by VectorForge | ${new Date().toISOString()}
================================================================================
`;

  await fs.writeFile(metadataPath, content, 'utf-8');

  logger.info(`Metadata: Generated listing info`, { metadataPath });

  return metadataPath;
}

export default { generateMetadataFile };
