'use client';

type Anchor = 'TOP_LEFT' | 'TOP' | 'TOP_RIGHT' | 'LEFT' | 'CENTER' | 'RIGHT' | 'BOTTOM_LEFT' | 'BOTTOM' | 'BOTTOM_RIGHT';
type Unit = 'IN' | 'CM';
type ResizeMode = 'PERCENT' | 'ABSOLUTE';
type Props = {
  resizeMode: ResizeMode; imageUnit: Unit; canvasUnit: Unit;
  imageWidth: number; imageHeight: number; imageDpi: number; canvasWidth: number; canvasHeight: number; canvasDpi: number;
  percent: number; maintainAspect: boolean; fill: 'WHITE' | 'BLACK'; anchor: Anchor;
  onResizeMode(value: ResizeMode): void; onImageUnit(value: Unit): void; onCanvasUnit(value: Unit): void;
  onImageWidth(value: number): void; onImageHeight(value: number): void; onImageDpi(value: number): void;
  onCanvasWidth(value: number): void; onCanvasHeight(value: number): void; onCanvasDpi(value: number): void;
  onPercent(value: number): void; onMaintainAspect(value: boolean): void; onFill(value: 'WHITE' | 'BLACK'): void; onAnchor(value: Anchor): void;
};
const numeric = (value: string) => Number(value);
const physical = (pixels: number, dpi: number, unit: Unit) => Number((unit === 'IN' ? pixels / dpi : pixels / dpi * 2.54).toFixed(3));
const pixelsFromPhysical = (value: number, dpi: number, unit: Unit) => value * dpi / (unit === 'IN' ? 1 : 2.54);
function field(label: string, value: number, change: (value: number) => void, step = 1, title?: string) { return <label title={title} className="text-sm font-semibold">{label}<input type="number" min="0.01" step={step} value={value} onChange={(event) => change(numeric(event.target.value))} className="mt-1 w-full rounded border p-2" /></label>; }
function unitSelector(label: string, value: Unit, change: (value: Unit) => void) { return <label className="text-sm font-semibold">{label}<select value={value} onChange={(event) => change(event.target.value as Unit)} className="mt-1 w-full rounded border p-2"><option value="IN">Inches</option><option value="CM">Centimeters</option></select></label>; }
export default function RasterLayoutControls(props: Props) {
  const imagePhysicalLabel = props.imageUnit === 'IN' ? 'inches' : 'cm'; const canvasPhysicalLabel = props.canvasUnit === 'IN' ? 'inches' : 'cm';
  return <div className="mt-3 space-y-4">
    <div><div className="flex flex-wrap items-center justify-between gap-2"><h3 title="Changes the actual pixel dimensions of the artwork before it is placed on the final canvas." className="font-semibold">Upscale / resize image</h3><div className="flex gap-2 text-sm"><label><input type="radio" checked={props.resizeMode === 'PERCENT'} onChange={() => props.onResizeMode('PERCENT')} /> By percent</label><label><input type="radio" checked={props.resizeMode === 'ABSOLUTE'} onChange={() => props.onResizeMode('ABSOLUTE')} /> Absolute size</label></div></div>
      {props.resizeMode === 'PERCENT' ? <div className="mt-2 grid grid-cols-2 gap-2">{field('Percent', props.percent, props.onPercent, 0.01, 'Scales both dimensions together from the selected working image, preserving its aspect ratio.')}<p className="self-end text-xs text-gray-600">Percentage resizing always preserves the aspect ratio.</p></div> : <div className="mt-2 grid grid-cols-2 gap-2">{field('Width (pixels)', props.imageWidth, props.onImageWidth)}{field('Height (pixels)', props.imageHeight, props.onImageHeight)}{unitSelector('Physical unit', props.imageUnit, props.onImageUnit)}{field(`Width (${imagePhysicalLabel})`, physical(props.imageWidth, props.imageDpi, props.imageUnit), (value) => props.onImageWidth(pixelsFromPhysical(value, props.imageDpi, props.imageUnit)), 0.01)}{field(`Height (${imagePhysicalLabel})`, physical(props.imageHeight, props.imageDpi, props.imageUnit), (value) => props.onImageHeight(pixelsFromPhysical(value, props.imageDpi, props.imageUnit)), 0.01)}{field('Image resolution (DPI)', props.imageDpi, props.onImageDpi)}<label className="col-span-2 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={props.maintainAspect} onChange={(event) => props.onMaintainAspect(event.target.checked)} />Maintain aspect ratio</label></div>}
    </div>
    <div className="border-t pt-4"><h3 title="Changes the final frame around the resized image. A smaller canvas clips the image at the chosen anchor; a larger canvas adds the chosen fill." className="font-semibold">Resize canvas</h3><div className="mt-2 grid grid-cols-2 gap-2">{field('Width (pixels)', props.canvasWidth, props.onCanvasWidth)}{field('Height (pixels)', props.canvasHeight, props.onCanvasHeight)}{unitSelector('Physical unit', props.canvasUnit, props.onCanvasUnit)}{field(`Width (${canvasPhysicalLabel})`, physical(props.canvasWidth, props.canvasDpi, props.canvasUnit), (value) => props.onCanvasWidth(pixelsFromPhysical(value, props.canvasDpi, props.canvasUnit)), 0.01)}{field(`Height (${canvasPhysicalLabel})`, physical(props.canvasHeight, props.canvasDpi, props.canvasUnit), (value) => props.onCanvasHeight(pixelsFromPhysical(value, props.canvasDpi, props.canvasUnit)), 0.01)}{field('Canvas resolution (DPI)', props.canvasDpi, props.onCanvasDpi)}<label title="Used only where the canvas is larger than the resized image. White is normally appropriate for JPG/PDF; transparent PNG output still treats exact white as transparent." className="text-sm font-semibold">Fill<select value={props.fill} onChange={(event) => props.onFill(event.target.value as 'WHITE' | 'BLACK')} className="mt-1 w-full rounded border p-2"><option value="WHITE">White</option><option value="BLACK">Black</option></select></label></div><label title="Controls which portion remains visible if the canvas clips the image, or where the image sits if the canvas is larger." className="mt-3 block text-sm font-semibold">Anchor<select value={props.anchor} onChange={(event) => props.onAnchor(event.target.value as Anchor)} className="mt-1 w-full rounded border p-2">{(['TOP_LEFT','TOP','TOP_RIGHT','LEFT','CENTER','RIGHT','BOTTOM_LEFT','BOTTOM','BOTTOM_RIGHT'] as const).map((value) => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></label></div>
  </div>;
}